### ISSUE TITLE
ImportError: cannot import name 'BingBrowser' from 'lagent.actions'

### ISSUE THREAD

**Issue by canqin001** [cnzzx/VSA#3]
Thanks for your amazing work! I am trying to run it at local. But it seems not working. Here is my error when running "python app.py". Could you please take a look? 

Traceback (most recent call last):
  File "/export/xgen-video/code/mmlm/VSA/app.py", line 2, in <module>
    from models.vsa_model import VisionSearchAssistant
  File "/export/xgen-video/code/mmlm/VSA/models/vsa_model.py", line 27, in <module>
    from lagent.actions import ActionExecutor, BingBrowser
ImportError: cannot import name 'BingBrowser' from 'lagent.actions'

**Comment by cnzzx** [comment]
Thanks for your interest. This might be related to the requirements problem. We've fixed the requirements and you can have a try.

**Comment by canqin001** [comment]
It works and thank you so much! But I have a new problem. After launching a demo (with command python app.py) and testing an instance, the code returns errors like this. Do you have any ideas about this?

Traceback (most recent call last):
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/gradio/queueing.py", line 703, in process_events
    response = await route_utils.call_process_api(
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/gradio/blocks.py", line 2014, in process_api
    result = await self.call_function(
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/gradio/blocks.py", line 1579, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/gradio/utils.py", line 691, in async_iteration
    return await anext(iterator)
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/gradio/utils.py", line 685, in __anext__
    return await anyio.to_thread.run_sync(
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/gradio/utils.py", line 668, in run_sync_iterator_async
    return next(iterator)
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/gradio/utils.py", line 829, in gen_wrapper
    response = next(iterator)
  File "/export/code/mmlm/VSA/app.py", line 24, in process_inputs
    for output, output_type in vsa.app_run(image, text, ground_classes = ground_classes):
  File "/export/code/mmlm/VSA/models/vsa_model.py", line 440, in app_run
    caption = self.vlm(det_image, inp)
  File "/export/code/mmlm/VSA/models/vsa_model.py", line 163, in __call__
    image_tensor = image_tensor.to(self.device, dtype=torch.float16)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.




If I use CUDA_VISIBLE_DEVICES=0,1,2 python app.py, it returns error as below:

File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling cublasLtMatmul with transpose_mat1 1 transpose_mat2 0 m 128 n 900 k 256 mat1_ld 256 mat2_ld 256 result_ld 128 abcType 0 computeType 77 scaleType 0





If I use CUDA_VISIBLE_DEVICES=0 python app.py, it returns error as below:

from pkg_resources import packaging  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/export/code/mmlm/VSA/app.py", line 102, in <module>
    vsa = VisionSearchAssistant()
  File "/export/code/mmlm/VSA/models/vsa_model.py", line 294, in __init__
    self.grounder = VisualGrounder(
  File "/export/code/mmlm/VSA/models/vsa_model.py", line 75, in __init__
    self.model = AutoModelForZeroShotObjectDetection.from_pretrained(model_path).to(device)
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2724, in to
    return super().to(*args, **kwargs)
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/export/miniconda3/envs/vsa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by cnzzx** [comment]
Well, we didn't have such an error. You should maybe provide more information. What's your environment, how many GPUs do you have, and what's their memory?

**Comment by canqin001** [comment]
Thank you for your reply. We have 8 A100 gpus with each of 40GB memory. May I ask your cuda version?

**Comment by cnzzx** [comment]
Our cuda version is 12.4 and we use 4090 GPUs.

**Comment by canqin001** [comment]
It was resolved. I just need change "cuda:x" into "cuda" and it works now.
